; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documenation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; There are numerous configurations of NightDriver that can be built here.  For example, the
; simplest is the DEMO config.  The HUB75 matrix project is the mesermizer.  You simply set
; default_envs to the project you wish to build.  There are project configs for various different
; NightDriver projects ranging from WiFi LED Strip to the simple lantern candle:
;
; demo          Simple WS2812B strip controller, runs a rainbow on PIN 5
; ledstrip      Waits for color data over wifi, so used for home displays, etc
; spectrum      M5StickCPlus project, a spectrum analyzer, on 48x16 WS2812B matrix
; mesmerizer    HUB75 info panel with audio effects, weather, info, etc,

[platformio]
default_envs = M5StickCPlus_8x64

; default_envs = spectrum
build_cache_dir = .pio/build_cache

extra_configs =
    custom_*.ini ; This file can be created in the root directory to store user defined devices and environments.

; ==================
; Base configuration
;
; Options that are used (or extended) in all device sections (and hence environments) are defined here

[base]
upload_port     = 
monitor_port    = 
build_type      = release
upload_speed    = 2000000
build_flags     = -std=gnu++2a
                  -g3
                  -Ofast
                  -ffunction-sections
                  -fdata-sections


build_src_flags = -Wformat=2                        ; Warnings for our code only, excluding libraries
                  -Wformat-truncation
                  -Wno-deprecated
                  -Wno-deprecated-declarations 
                  -Wstack-usage=4096

# Exclude libraries that we don't control from 'pio check'.
# format is error number(optional :path_with_wildcards(optional :line_number))
check_flags     = cppcheck: --suppress=*:*src/uzlib/src/*

lib_deps        = crankyoldgit/IRremoteESP8266  @ ^2.7.20
                  fastled/FastLED               @ ^3.8.0
                  adafruit/Adafruit BusIO       @ ^1.9.1
                  adafruit/Adafruit GFX Library @ ^1.10.12
                  olikraus/U8g2                 @ ^2.28.8
                  kosme/arduinoFFT              @ ^2.0
                  esp32async/ESPAsyncWebServer  @ ^3.7.0
                  bblanchon/ArduinoJson         @ ^7.3.0
                  thomasfredericks/Bounce2      @ ^2.7.0
                  https://github.com/PlummersSoftwareLLC/RemoteDebug
                  QRCode                        @ ^0.0.1
                  Bodmer/TJpg_Decoder           @ ^1.0.8
                  plageoj/UrlEncode             @ ^1.0.1
                  ; https://github.com/PlummersSoftwareLLC/SmartMatrix.git
                  https://github.com/PlummersSoftwareLLC/GifDecoder.git
                  bitbank2/AnimatedGIF @ ^1.4.7

; This partition table attempts to fit everything in 4M of flash.

board_build.partitions = config/partitions_custom.csv


; =================================
; Build flags for enabling a remote
;
; You can set these here once to match your setup; they are then included in all environments
; that are configured to be used with a remote.

[remote_flags]
build_flags     = -D_IR_ENABLE_DEFAULT_=false       ; Don't automatically include every remote control decoder
                  -DDECODE_NEC=true                 ; Enable whichever you need for your remote.  Try not disabling
                                                    ; above to figure out which it is.

; ===============
; Device sections
;
; Sections starting with "dev_" contain general settings for a particular type of device.
; They extend the "base" config, both in general and in terms of build flags and dependencies,
; where applicable.

[dev_esp32]
extends         = base
board           = esp32dev
monitor_speed   = 115200
upload_speed    = 921600

[dev_esp32-s3]
extends         = base
board           = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
monitor_speed   = 115200
upload_speed    = 1000000


[dev_m5]
extends         = base
monitor_speed   = 115200
upload_speed    = 1500000
build_flags     = -DUSE_SCREEN=1
                  ${base.build_flags}
lib_deps        = ${base.lib_deps}
                  m5stack/M5Unified @ ^0.1.17

[dev_m5stick-c]
extends         = dev_m5
board           = m5stick-c
build_flags     = -DM5STICKC=1
                  ${dev_m5.build_flags}

[dev_m5stick-c-plus]
extends         = dev_m5
board           = m5stick-c                         ; Requires the M5StickC Plus (note the Plus)
build_flags     = -DM5STICKCPLUS=1
                  ${dev_m5.build_flags}
                  
[dev_m5stick-c-plus-8x64]
extends         = dev_m5
board           = m5stick-c                         ; Requires the M5StickC Plus (note the Plus)
build_flags     = -DM5STICKCPLUS=1
                  ${dev_m5.build_flags}

[dev_mesmerizer]
extends         = dev_wrover
upload_speed    = 2000000
board_build.partitions  = config/partitions_custom_8M.csv
board_upload.flash_size = 8MB


; ===================
; Capability sections
;
; The following sections contain build flags and/or dependencies to enable a particular capability
; or module in specific environments. They applicable option(s) - build_flags, lib_deps or both -
; are included in the environments in question.
;
; Note that these sections do not extend "base", as they are basically feature toggles.


; Build flags for use of PSRAM
[psram_flags]
build_flags     = -DUSE_PSRAM=1
                  -DBOARD_HAS_PSRAM=1
                  -mfix-esp32-psram-cache-issue


; Build flags for enabling high precision Unity double
[unity_double_flags]
build_flags     = -DUNITY_INCLUDE_DOUBLE
                  -DUNITY_DOUBLE_PRECISION=1e-12    ; Make doubles real 8 byte doubles

; ================================================================
; Basic environment section, automatically inherited by all others
;

[env]
platform        = platformio/espressif32@^6.3.0
framework       = arduino
build_type      = release
build_unflags   = -std=gnu++11
lib_extra_dirs  = ${PROJECT_DIR}/lib
monitor_filters = esp32_exception_decoder
extra_scripts   = pre:tools/bake_site.py
                  post:tools/merge_image.py
board_build.embed_files = site/dist/index.html.gz
                          site/dist/index.js.gz
                          site/dist/favicon.ico.gz
                          assets/gif/pacman.gif
board_build.embed_txtfiles = config/timezones.json

; ================================================================
; Common project configurations
;

[mesmerizer_config]
build_flags     = -DMESMERIZER=1
                  -DUSE_HUB75=1
                  -DSHOW_VU_METER=1
                  ${psram_flags.build_flags}
                  ${remote_flags.build_flags}

lib_deps        = https://github.com/PlummersSoftwareLLC/SmartMatrix.git
                  https://github.com/PlummersSoftwareLLC/GifDecoder.git
                  bitbank2/AnimatedGIF @ ^1.4.7

board_build.embed_files = assets/bmp/brokenclouds.jpg
                          assets/bmp/brokencloudsnight.jpg
                          assets/bmp/clearsky.jpg
                          assets/bmp/clearnight.jpg
                          assets/bmp/fewclouds.jpg
                          assets/bmp/fewcloudsnight.jpg
                          assets/bmp/lowreslogo.jpg
                          assets/bmp/mist.jpg
                          assets/bmp/mistnight.jpg
                          assets/bmp/rain.jpg
                          assets/bmp/rainnight.jpg
                          assets/bmp/scatteredclouds.jpg
                          assets/bmp/scatteredcloudsnight.jpg
                          assets/bmp/showerrain.jpg
                          assets/bmp/showerrainnight.jpg
                          assets/bmp/snow.jpg
                          assets/bmp/snownight.jpg
                          assets/bmp/thunderstorm.jpg
                          assets/bmp/thunderstormnight.jpg
                          assets/gif/colorsphere.gif
                          assets/gif/atomic.gif
                          assets/gif/pacman.gif
                          assets/gif/threerings.gif
                          assets/gif/banana.gif
                          assets/gif/tesseract.gif
                          assets/gif/firelog.gif
                          assets/gif/nyancat.gif
                          ${env.board_build.embed_files}

; ====================
; Project environments
;
; These are the actual environments defined in this file. Each configures one project for one
; specific device. They extend the "dev_" config for the device in question, both in general
; and in terms of build flags and dependencies, where applicable.
;
; Note: when adding a new environment to the list, don't forget to explicitly add the device
; section's build_flags and lib_deps options (using ${dev_<device>.<option>}) if you define
; either or both in the environment you add. PlatformIO does not merge them automatically.
; In addition to the build_flags and lib_deps of the device, capability flags and/or dependencies
; can be included where appropriate.

;=========

[env:demo]
extends         = dev_esp32
build_flags     = -DDEMO=1
                  ${dev_esp32.build_flags}

; This is the basic DEMO project again, but expanded to work on the M5, which means it can draw to
; the built in LCD.  It's made so that you can connect to the small 4-pin connector on the M5,
; so it sends power and ground as well as data on PIN 32.



; This is largely the same as the m5demo above except it links to the PLUS version of the lib
[env:m5plusdemo]
extends         = dev_m5stick-c-plus
build_flags     = -DM5DEMO=1
                  ${dev_m5stick-c-plus.build_flags}


;=============

[env:spectrum]
extends         = dev_m5stick-c-plus
build_flags     = -DSPECTRUM=1
                  -DSHOW_VU_METER=1
                ;   ${remote_flags.build_flags}
                  ${dev_m5stick-c-plus.build_flags}
board_build.partitions = config/partitions_custom_noota.csv

[env:M5StickCPlus_8x64]
extends         = dev_m5stick-c-plus-8x64
build_flags     = -DSPECTRUM=1
                  -DSHOW_VU_METER=1
                  -DUSE_WS281X=1
                  ; -DUSE_HUB75=1
                  ; -DMATRIX_WIDTH=64
                  ; -DMATRIX_HEIGHT=8
                  -DMATRIX_1D=1
                  -DMATRIX_GIF=1
                  -DTOGGLE_BUTTON_1=37
                  -DTOGGLE_BUTTON_2=39
                  -DNUM_INFO_PAGES=2
                  -DLED_PIN0=32
                  ; -DENABLE_REMOTE=0
                ;   ${remote_flags.build_flags}
                  ${dev_m5stick-c-plus-8x64.build_flags}
board_build.partitions = config/partitions_custom_noota.csv


[env:helmet]
extends         = dev_m5stick-c-plus
build_flags     = -DHELMET=1
                  -DSHOW_VU_METER=1
                  ${remote_flags.build_flags}
                  ${dev_m5stick-c-plus.build_flags}
board_build.partitions = config/partitions_custom_noota.csv


;===============

